[package]
name = "wikidata-to-surrealdb"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surrealdb = "1.0"
tokio = "1.35"
wikidata = "0.3.1"
bzip2 = { version = "0.4", features = ["tokio"] }
lazy_static = "1.4"
indicatif = "0.17"
