[package]
name = "wikidata-to-surrealdb"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surrealdb = { version = "1.5", features = ["protocol-ws", "kv-mem"] }
tokio = { version = "1.39", features = ["time"] }
futures = "0.3"
wikidata = "1.1"
bzip2 = { version = "0.4", features = ["tokio"] }
lazy_static = "1.5"
indicatif = "0.17"
rand = "0.8"

[dev-dependencies]
surrealdb = { version = "1.5", features = ["kv-mem"] }
criterion = { version = "0.5", features = ["async_tokio"] }
pprof = { version = "0.13", features = ["criterion", "protobuf-codec"] }

[[bench]]
name = "bench"
harness = false
