version: "3"
services:
    surrealdb:
        container_name: surrealdb
        image: surrealdb/surrealdb:latest
        env_file:
        - .env
        entrypoint: 
        - /surreal 
        - start 
        - --user
        - $DB_USER
        - --pass
        - $DB_PASSWORD
        - file:/data/surrealdb
        ports:
            - 8000:8000
        volumes:
            - ./data:/data
        networks:
            - surrealdb

    wikidata-to-surrealdb:
        container_name: wikidata-to-surrealdb
        image: ghcr.io/nexveridian/ark-invest-api-rust-data:latest
        env_file:
            - .env
        environment:
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - WIKIDATA_LANG=$WIKIDATA_LANG
            - FILE_FORMAT=$FILE_FORMAT
            - FILE_NAME=$FILE_NAME
        restart: no
        depends_on:
            - surrealdb
        volumes:
            - ./data:/data
        networks:
            - surrealdb

volumes:
    data:

networks:
    surrealdb:
