[alias]
t = "nextest run"
# https://github.com/tikv/pprof-rs?tab=readme-ov-file#use-with-pprof
profile = "bench --bench bench -- --profile-time 10"

[build]
target-dir = "target/target"

[unstable]
codegen-backend = true

[profile.release]
codegen-backend = "cranelift"

[profile.dev]
codegen-backend = "cranelift"
